package com.tdkankan.greendao.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tdkankan.greendao.model.Bookinfodb;

import com.tdkankan.greendao.green.BookinfodbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookinfodbDaoConfig;

    private final BookinfodbDao bookinfodbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookinfodbDaoConfig = daoConfigMap.get(BookinfodbDao.class).clone();
        bookinfodbDaoConfig.initIdentityScope(type);

        bookinfodbDao = new BookinfodbDao(bookinfodbDaoConfig, this);

        registerDao(Bookinfodb.class, bookinfodbDao);
    }
    
    public void clear() {
        bookinfodbDaoConfig.clearIdentityScope();
    }

    public BookinfodbDao getBookinfodbDao() {
        return bookinfodbDao;
    }

}
